config/routes.rb
Rails.application.routes.draw do

  get 'feeds/home'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    resources :friendships, :path => "friends"
    
  end

  resources :transactions, only: [:create, :new, :index]
  resources :friendships, only: [:create, :new, :index, :edit, :update]
  resources :relationships, only: [:create, :new, :index]

  get '/users/:id/edit_balance', to: 'users#edit_balance', as:'edit_balance'
  post '/users/:id/edit_balance', to: 'users#update_balance',  as:'update_balance'

  get '/users/:id/add_friends', to: 'users#add_friends', as:'add_friends'
  post '/users/:id/add_friends', to: 'users#update_friends', as:'update_friends'

  get '/users/:id/friend_relationship/:id', to: 'users#friend_relationship', as:'friend_relationship'

  root 'feeds#home'

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def home
    if !user_signed_in?
      redirect_to new_user_registration_path
    end
    
    @biggest = Transaction.biggest

  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/home.html.erb
<h1>This is your profile <%= current_user.name %></h1>


<h3>Which one of your friends do you want to borrow money from?</h3>


<ul>
<% current_user.friends.each do |friend| %>

  <li><%= link_to friend.name, user_friendship_path(current_user.id, friend.id) %> -<%= link_to friend.friend_relationship(current_user.id, friend.id), friend_relationship_path(current_user.id, friend.id)%></li>
<% end %>
</ul>

<h3> Add your friends here</h3>
<%= link_to "Add Friends", add_friends_path(:id=>current_user.id) %>

<h3>These are the top five biggest lent amounts!</h3>
<ul>
  <% @biggest.each do |transaction| %>
  <li><%= transaction.lender.name %> lent <%= transaction.amount%> to <%= transaction.borrower.name%></li>
  <% end %>
</ul>