config/routes.rb
Rails.application.routes.draw do

  get 'feeds/home'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    resources :friendships, :path => "friends"
    
  end

  resources :transactions, only: [:create, :new, :index]
  resources :friendships, only: [:create, :new, :index, :edit, :update]
  resources :relationships, only: [:create, :new, :index]

  get '/users/:id/edit_balance', to: 'users#edit_balance', as:'edit_balance'
  post '/users/:id/edit_balance', to: 'users#update_balance',  as:'update_balance'

  get '/users/:id/add_friends', to: 'users#add_friends', as:'add_friends'
  post '/users/:id/add_friends', to: 'users#update_friends', as:'update_friends'

  get '/users/:id/friend_relationship/:id', to: 'users#friend_relationship', as:'friend_relationship'

  root 'feeds#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [ :facebook, :google_oauth2]

  has_many :borrowed, :foreign_key => 'borrower_id', :class_name => 'Transaction'
  has_many :lent_out, :foreign_key => 'lender_id', :class_name => 'Transaction'
  has_many :lenders, through: :borrowed
  has_many :borrowers, through: :lent_out
  has_many :debits, foreign_key: 'borrower_id'
  has_many :debits, foreign_key: 'lender_id'
  has_many :credits, foreign_key: 'lender_id'
  has_many :credits, foreign_key: 'borrower_id'

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :relationships


  scope :lent_amount, -> { order ('lent_out DESC LIMIT 5') }

  attr_accessor :flash_notice


  accepts_nested_attributes_for :friends

  def friends_attributes=(attributes)

  attributes["friend_ids"].each do |attribute|
    if attribute != ""
     friend = User.find_or_create_by(id: attribute)
        if !self.friends.include?(friend)
          self.friends << friend
        end
      end
   end
   self.save
  end

  def friends_attributes
    self.friends.uniq
  end




  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end




  def add_money(money)
    self.balance + money
  end

    def total_borrowed_from(lender_id)
      borrowed.where(lender_id: lender_id).sum(:amount)
    end

    def total_lended(borrower_id)
      lent_out.where(borrower_id: borrower_id).sum(:amount)
    end

    def unique_lenders
      lenders.distinct
    end

    def unique_borrowers
      borrowers.distinct
    end

    def total_amount_due(current_user, lender)
       debit= Debit.find_or_create_by(borrower_id: current_user.id, lender_id: lender.id)
       credit = Credit.find_or_create_by(borrower_id: current_user.id, lender_id: lender.id)

       debit.amount - credit.amount
    end

    def borrower_total_amount_due(current_user, borrower)
       debit= Debit.find_or_create_by(borrower_id: borrower.id, lender_id: current_user.id)
       credit = Credit.find_or_create_by(borrower_id: borrower.id, lender_id: current_user.id)

       debit.amount - credit.amount
    end

    def lender_amount_not_zero(current_user)
      collection = []
      unique_lenders.each do |lender|

        if lender.total_amount_due(current_user, lender) != 0
          collection << lender
        end
      end
      collection
    end

    def borrower_amount_not_zero(current_user)
      collection = []
      unique_borrowers.each do |borrower|

        if borrower_total_amount_due(current_user, borrower) != 0
          collection << borrower
        end
      end
      collection
    end

    def overpaid_lender(current_user)
      collection = []
      lender_amount_not_zero(current_user).each do |lender|
      if total_amount_due(current_user, lender) < 0
        collection << lender
        end
      end
      collection
    end

    def display_overpaid_amount(current_user, user)
      current_user.overpaid_lender(current_user).include?(user)
    end

    def overpaid_borrower(current_user)
      collection = []
      borrower_amount_not_zero(current_user).each do |borrower|
      if borrower.borrower_total_amount_due(current_user, borrower) < 0
        collection << borrower
        end
      end
      collection
    end

def return_json

    return_val = []
    self.friends.each do |friend|
      obj = {}
      obj[:friend] = friend
      obj[:amount] = self.total_amount_due(self, friend)
      obj[:borrower] = self.borrower_total_amount_due(self, friend)
      return_val << obj
    end
    return_val
end

def friend_relationship(current_user, friend_id)

  rel = Friendship.find_by(user_id: current_user, friend_id: friend_id)
  rel.relationship
end

def update_friends(user_name, e)
  if user_name !=""
    person = User.new(name:user_name.strip, email: e)
    person.save(validate:false)
    new_friend =Friendship.create(user_id:self.id, friend_id:person.id)
  end
end


def create_this_transaction(current_user, friend, amount_params)
  if amount_params != "" && amount_params != "0"
    @transaction = Transaction.new(lender_id: current_user.id, borrower_id: friend, amount: amount_params)

    if @transaction.save
    else
      self.flash_notice = @transaction.errors.full_messages[0]

    end
  end
end

def setting_default_relationship(drop_params)
  if drop_params[:relationship_id].to_i != 0
    word = drop_params[:relationship_id].to_i
  else
    word = 1
  end
  word
end

def setting_relationship_variable(current_user, new_user_info, new_word)
  new_friend_relationship = Friendship.find_by(user_id: current_user.id, friend_id: new_user_info)
  new_friend_relationship.update(relationship: new_word.description)
end


def creating_relationship_transaction_friend(user_name, rel_params, drop_params, amount_params, current_user )
  if user_name != ""
    if rel_params[:description] == ""
    word = self.setting_default_relationship(drop_params)
    new_user_info = User.last.id
    new_word = Relationship.find(word)
    self.setting_relationship_variable(current_user, new_user_info, new_word)
    self.create_this_transaction(current_user, new_user_info, amount_params)
    end
  else
    if rel_params[:description] != ""
      self.setting_default_relationship(drop_params)
      new_word =Relationship.find_or_create_by(description: rel_params[:description])
      new_user_info = User.last.id

      self.setting_relationship_variable(current_user, new_user_info, new_word)
      friend_id = User.last.id
      self.create_this_transaction(current_user, friend_id, amount_params)
    end
  end
end

def update_relationship_variable(word, friend)
  new_word = Relationship.find(word)
  friend.update(relationship: new_word.description)
end


def create_attributes_with_existing_friends(drop_params, rel_params, friend_params, user_params, current_user, amount_params)
    word = self.setting_default_relationship(drop_params)
    if rel_params[:description] == ""

      if friend_params[:friend_id] != friend_params[:user_id]
        friend = Friendship.find_or_create_by(friend_params)

        self.update_relationship_variable(word, friend)

      end
      user_params[:friends_attributes][:friend_ids].each do |friend_att|
        if friend_att != ""
          friend = User.find(friend_att)
          set_friend = Friendship.find_or_create_by(friend_id: friend.id, user_id: current_user.id)
          self.update_relationship_variable(word, set_friend)
          friend = friend.id
          self.create_this_transaction(current_user, friend, amount_params)
        end
      end
    else
      new_word =Relationship.find_or_create_by(description: rel_params[:description])

      user_params[:friends_attributes][:friend_ids].each do |friend_att|

        if friend_att != ""
          friend = User.find(friend_att)
          if friend.id != current_user.id

            set_relationship = Friendship.find_or_create_by(friend_id: friend.id, user_id: current_user.id)
            set_relationship.update(relationship: new_word.description)
            friend = friend.id

            self.create_this_transaction(current_user, friend, amount_params)
        end
      end
    end
  end
end




  #   if self.lender_ids.include?(lender.to_i)
  #     lender = User.find(lender.to_i)
  #   end
  # end

end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController


  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in?
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit, :edit_balance, :update_balance, :friend_relationship]
  after_filter :flash_notice

  def flash_notice

    if !@user.flash_notice.blank?
          flash[:notice] = @user.flash_notice
        
       end
  end

@@email = 22

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def index
    @users = User.all

    respond_to do |f|
      f.html { render :index }
      f.json { render json: @users }
    end
  end

  def new
  end

  def create

  end

  def edit
  end

  def edit_balance

  end

  def update_balance

    @user.update(balance: @user.add_money(params[:balance].to_i))
    redirect_to user_path(@user)
  end

  def add_friends
    @relationships = Relationship.all
    @user = current_user
  end

  def update_friends

  end

  def friend_relationship
    @relationships = Relationship.all
    @relationship = Relationship.new
  end

  def show
    @transaction = Transaction.new
    @friends = @user.friends
    @user.return_json

    respond_to do |f|
      f.html { render :show }
      f.json { render json: [@user.return_json] }
    end
  end

  def update
    number = Random.rand(10000000)
    letters = [*('A'..'Z')].sample(8).join
    user_name = params[:user][:users][:name]
    e = "#{number}#{letters}@gmail.com"
    @user = User.find(params[:id])
    @user.update(user_params)
    @user.update_friends(user_name, e)
    user_rel_params = rel_params
    @user.creating_relationship_transaction_friend(user_name, user_rel_params, drop_params, amount_params, current_user )
    @user.create_attributes_with_existing_friends(drop_params, rel_params, friend_params, user_params, current_user, amount_params)
    if !@user.flash_notice.blank?
      redirect_to (:back)
    else
      flash[:message] = "Added Friends Successfully"
      redirect_to root_path
    end
  end





private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:friends_attributes => [:friend_ids=>[]], users_attributes: [:name])
  end

  def drop_params
    params.require(:description).permit(:relationship_id)
  end

  def friend_params
    params.require(:user)[:relationships].permit(:friend_id, :user_id)
  end
  def rel_params
    params.require(:user)[:relationships].permit(:description)
  end
  def amount_params
    params.require(:user)[:transactions].permit(:amount)[:amount]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_friends.html.erb
<h2>Adding new friends</h2>


<%= form_for @user do |f| %>

<h4>How close are you to these people?  Use the drop down box or create a unique relationship</h4>

<%= f.fields_for :relationships, Relationship.new do |relationship| %>
<%=select("description", "relationship_id", @relationships.collect {|r| [ r.description, r.id ] }, { :include_blank => true })%>
<%= relationship.label :description %>
<%= relationship.text_field :description %>
<%= relationship.hidden_field :friend_id, value: @user.id %>
<%= relationship.hidden_field :user_id, value: current_user.id %>
<% end %><br><br>

<h4>Find your friends! </h4>
  <%= f.fields_for :friends_attributes do |u| %>
  <%= u.collection_check_boxes :friend_ids, User.all, :id, :name %>
<h5>Would you like to lend them money? (Optional): </h5>
  <%=f.fields_for :transactions, Transaction.new do |transaction|%>
  <%= transaction.text_field :amount%>
  <% end %>
  <br><%= u.submit "Add Friends"%>
<% end %><br>


<h3>Add a friend that isnt here on this list!</h3>

  <%= f.fields_for :users, User.new do |user| %>
  <%= user.label :name %>
  <%= user.text_field :name %>
  <%= f.submit "Add Friend" %>
  <% end %>
<% end %>

app/views/users/edit_balance.html.erb
<h1>It must be pay day!!! </h1>




<%= form_tag(update_balance_path) do |f| %>
  <h4>How much did you make? </h4>
  $<%= number_field_tag :balance  %>

  <%= submit_tag "Make Me Richer" %>
<% end %>

app/views/users/friend_relationship.html.erb
<h3>How close are you to <%=@user.name%>? </h3>


<%= form_for @relationship do |f| %>
<%=select("description", "relationship_id", @relationships.collect {|r| [ r.description, r.id ] }, { :include_blank => true })%>


<%= f.label :description %>
<%= f.text_field :description %>
<%= f.hidden_field :friend_id, value: @user.id %>
<%= f.hidden_field :user_id, value: current_user.id %>

  <%=f.submit%>
<% end %>

app/views/users/index.html.erb
<ul>
<% @users.each do |t| %>
  <li><%= t.name %></li>
<% end %>
</ul>

app/views/users/show.html.erb
<% if current_user != @user %>
  <h1>Hey <%= current_user.name%>! You only visit when you need money</h1>
<% else %>
  <h1>Hi <%= @user.name %></h1>
  <h3> This is sort of your profile page</h3>
<% end %>


<table>
  <tr>
    <% if current_user != @user %>
      <td>This is <%= @user.name %>'s balance. (Do you really need the money that bad?): <h3>$<%= @user.balance %></h3></td>
    <% else %>
      <td>This is your balance: <%= @user.balance %></td>
      <td><%= link_to 'Edit', edit_balance_path(@user) %></td>
    <% end %>
  </tr>
</table>



<% if current_user != @user %>

  <%= form_for @transaction do |f| %>
    <h4>How much are you taking from poor <%= @user.name%>?
      <%if current_user.total_amount_due(current_user, @user) > 0 %>
      You already owe $<%= current_user.total_amount_due(current_user, @user) %><% end %></h4>

    <%if current_user.total_amount_due(current_user, @user) > 0%>
    <h4></h4>
    <% end %>
    $<%= f.text_field :amount %>
    <%= f.hidden_field :lender_id, value: @user.id %>
    <%= f.submit "Your friend is so generous" %>
  <% end %><br>


  <% if @user.total_amount_due(current_user, @user) > 0 %>
    <h4>Repay what you owe. <%= @user.name %> kind of needs it.</h4>
    <%= form_for @transaction do |f| %>
      $<%= f.text_field :amount %>
      <%= f.hidden_field :lender_id, value: @user.id %>
      <%= f.hidden_field :lending, value: false %>
      <%= f.submit "You're doing the right thing" %>
      <% end %>
  <% end %>
<% end %>

<%if current_user != @user %>
<div>
  <% if @user.display_overpaid_amount(current_user, @user) %>
  <h2>Actually <%=@user.name%> owes you $<%= @user.total_amount_due(current_user, @user).abs%>. Maybe you overpaid</h2>
  <% end %>
</div>
<% end %>

<% if current_user == @user %>
<div>
  <%if !@user.overpaid_lender(current_user).empty?%>
    <h4>Seems like you overpaid</h4>
    <ul>
      <% @user.overpaid_lender(current_user).each do |lender| %>

      <li><%=link_to(lender.name, user_friendship_path(@user.id, lender.id))%> - $<%= @user.total_amount_due(current_user, lender).abs%></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% end %>


<% if current_user != @user%>
  <div>
      <h4><%= "#{@user.name} borrowed from #{@user.borrowed.pluck(:lender_id).uniq.count} people" %></h4>
  </div>
<% end %>


      <% if !@user.lender_amount_not_zero(current_user).empty? %>
        <h4>These are the people you owe.</h4>
          <ul>
            <% @user.lender_amount_not_zero(current_user).each do |lender| %>

              <% if !@user.overpaid_lender(current_user).include?(lender)%>
            <li><%=link_to lender.name, user_friendship_path(@user.id, lender.id) %> - $<%= @user.total_amount_due(current_user, lender) %></li>
            <% end %>
          <% end %>
          </ul>
    <% end %>
</div>

<% if current_user == @user %>
<div>

  <%if !@user.overpaid_borrower(current_user).empty?%>
    <h4>Seems like THESE are the people that overpaid YOU. </h4>
    <ul>
      <% @user.overpaid_borrower(current_user).each do |borrower| %>
      <li><%=link_to borrower.name, user_friendship_path(@user.id, borrower.id)%> - $<%= borrower.borrower_total_amount_due(current_user, borrower).abs%></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% end %>




<% if current_user == @user %>
<div>
  <% if !@user.borrower_amount_not_zero(current_user).empty? %>
    <h3>These are all of the people that you need to hunt</h3>
    <ul>
        <% @user.borrower_amount_not_zero(current_user).each do |borrower| %>
        <% if !@user.overpaid_borrower(current_user).include?(borrower)%>
        <li><%=link_to borrower.name, user_friendship_path(@user.id, borrower.id) %> - $<%= @user.borrower_total_amount_due(current_user, borrower) %></li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</div>
<% end %>




<%if current_user == @user %>
  <button id="friends">View All Friends</button>
  <div id="hide"></div>
    <div id="allFriends"></div>

  <button id="lenders">View All Lenders</button>
    <div id="hideL"></div>
    <div id="allLenders"></div>
  <button id="borrowers">View All Borrowers</button>
  <div id="hideB"></div>
    <div id="allBorrowers"></div>
<% end %>