config/routes.rb
Rails.application.routes.draw do

  get 'feeds/home'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :users do
    resources :friendships, :path => "friends"
    
  end

  resources :transactions, only: [:create, :new, :index]
  resources :friendships, only: [:create, :new, :index, :edit, :update]
  resources :relationships, only: [:create, :new, :index]

  get '/users/:id/edit_balance', to: 'users#edit_balance', as:'edit_balance'
  post '/users/:id/edit_balance', to: 'users#update_balance',  as:'update_balance'

  get '/users/:id/add_friends', to: 'users#add_friends', as:'add_friends'
  post '/users/:id/add_friends', to: 'users#update_friends', as:'update_friends'

  get '/users/:id/friend_relationship/:id', to: 'users#friend_relationship', as:'friend_relationship'

  root 'feeds#home'

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
<% end %>

app/views/layouts/_show.html.erb
<% if current_user != @user %>
  <h1>Hey <%= current_user.name%>! You only visit when you need money</h1>
<% else %>
  <h1>Hi <%= @user.name %></h1>
  <h3> This is sort of your profile page</h3>
<% end %>


<table>
  <tr>
    <% if current_user != @user %>
      <td>This is <%= @user.name %>'s balance. (Do you really need the money that bad?): <h3>$<%= @user.balance %></h3></td>
    <% else %>
      <td>This is your balance: <%= @user.balance %></td>
      <td><%= link_to 'Edit', edit_balance_path(@user) %></td>
    <% end %>
  </tr>
</table>



<% if current_user != @user %>

  <%= form_for @transaction do |f| %>
    <h4>How much are you taking from poor <%= @user.name%>?
      <%if current_user.total_amount_due(current_user, @user) > 0 %>
      You already owe $<%= current_user.total_amount_due(current_user, @user) %><% end %></h4>

    <%if current_user.total_amount_due(current_user, @user) > 0%>
    <h4></h4>
    <% end %>
    $<%= f.text_field :amount %>
    <%= f.hidden_field :lender_id, value: @user.id %>
    <%= f.submit "Your friend is so generous" %>
  <% end %><br>


  <% if @user.total_amount_due(current_user, @user) > 0 %>
    <h4>Repay what you owe. <%= @user.name %> kind of needs it.</h4>
    <%= form_for @transaction do |f| %>
      $<%= f.text_field :amount %>
      <%= f.hidden_field :lender_id, value: @user.id %>
      <%= f.hidden_field :lending, value: false %>
      <%= f.submit "You're doing the right thing" %>
      <% end %>
  <% end %>
<% end %>

<%if current_user != @user %>
<div>
  <% if @user.display_overpaid_amount(current_user, @user) %>
  <h2>Actually <%=@user.name%> owes you $<%= @user.total_amount_due(current_user, @user).abs%>. Maybe you overpaid</h2>
  <% end %>
</div>
<% end %>

<% if current_user == @user %>
<div>
  <%if !@user.overpaid_lender(current_user).empty?%>
    <h4>Seems like you overpaid</h4>
    <ul>
      <% @user.overpaid_lender(current_user).each do |lender| %>
      <li><%=link_to lender.name, user_path(lender)%> - $<%= @user.total_amount_due(current_user, lender).abs%></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% end %>


<% if current_user != @user%>
  <div>
      <h4><%= "#{@user.name} borrowed from #{@user.borrowed.pluck(:lender_id).uniq.count} people" %></h4>
  </div>
<% end %>


      <% if !@user.lender_amount_not_zero(current_user).empty? %>
        <h4>These are the people you owe.</h4>
          <ul>
            <% @user.lender_amount_not_zero(current_user).each do |lender| %>

              <% if !@user.overpaid_lender(current_user).include?(lender)%>
            <li><%=link_to lender.name, user_path(lender) %> - $<%= @user.total_amount_due(current_user, lender) %></li>
            <% end %>
          <% end %>
          </ul>
    <% end %>
</div>

<% if current_user == @user %>
<div>

  <%if !@user.overpaid_borrower(current_user).empty?%>
    <h4>Seems like THESE are the people that overpaid YOU. </h4>
    <ul>
      <% @user.overpaid_borrower(current_user).each do |borrower| %>
      <li><%=link_to borrower.name, user_path(borrower)%> - $<%= borrower.borrower_total_amount_due(current_user, borrower).abs%></li>
    <% end %>
  </ul>
  <% end %>
</div>
<% end %>




<% if current_user == @user %>
<div>
  <% if !@user.borrower_amount_not_zero(current_user).empty? %>
    <h3>These are all of the people that you need to hunt</h3>
    <ul>
        <% @user.borrower_amount_not_zero(current_user).each do |borrower| %>
        <% if !@user.overpaid_borrower(current_user).include?(borrower)%>
        <li><%=link_to borrower.name, user_path(borrower) %> - $<%= @user.borrower_total_amount_due(current_user, borrower) %></li>
        <% end %>
      <% end %>
    </ul>
  <% end %>
</div>
<% end %>

<%if current_user == @user %>
<button id="friends">View All Friends</button>
<div id="hide"></div>
  <div id="allFriends"></div>

<button id="lenders">View All Lenders</button>
  <div id="hideL"></div>
  <div id="allLenders"></div>
<button id="borrowers">View All Borrowers</button>
<div id="hideB"></div>
  <div id="allBorrowers"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BallerOnYourBudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/messages' %>



<%= yield %>


<br><br>
<% if !user_signed_in? %>
  <%= link_to "Sign up", new_user_registration_path %><br>
  <%= link_to "Sign in", new_user_session_path %><br>
<% else %>
  <%= link_to "Sign out" , destroy_user_session_path, :method => :delete %><br>
  <%= link_to "Profile", user_path(current_user) %><br>
  <%= link_to "Feed", root_path  %>
<% end %>

</body>
</html>